nc: 1

scales: # model compound scaling constants, i.e. 'model=yolov5n.yaml' will call yolov5.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [1.0, 1.0, 1024]

backbone:
  [[-1, 1, Conv, [32, 6, 2, 2]],

   [0, 1, SPPF, [32, 5]],

   [0, 1, SPPF, [32, 5]],

   [0, 1, SPPF, [32, 5]],
  ]

head:
  [
   [[1, 2, 3], 1, Detect, [nc]],
  ]

chain_num: 3
chains:
  {
    'backbone': [[1], [2], [3]],
    'head': [[], [], []]
  }

age: 1
fitness: 0.000001
final_fitness: 0.0
fitness_history: []
